In [4]:
from google.colab import drive

drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [8]:
import os
import glob
import pandas as pd
from os import listdir
('/content/gdrive/My Drive/Flight/2016')

'/content/gdrive/My Drive/Flight/2016'

In [12]:
df17 = pd.concat(map(pd.read_csv, glob.glob('/content/gdrive/My Drive/Flight/2016/*.csv')))

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (48,77,84,85) have mixed types. Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (77) have mixed types. Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (48,69,76,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [13]:
df17

        Year  Quarter  Month  ...  Div5WheelsOff  Div5TailNum Unnamed: 109
0       2016        3      7  ...            NaN          NaN          NaN
1       2016        3      7  ...            NaN          NaN          NaN
2       2016        3      7  ...            NaN          NaN          NaN
3       2016        3      7  ...            NaN          NaN          NaN
4       2016        3      7  ...            NaN          NaN          NaN
...      ...      ...    ...  ...            ...          ...          ...
450933  2016        4     11  ...            NaN          NaN          NaN
450934  2016        4     11  ...            NaN          NaN          NaN
450935  2016        4     11  ...            NaN          NaN          NaN
450936  2016        4     11  ...            NaN          NaN          NaN
450937  2016        4     11  ...            NaN          NaN          NaN

[5617658 rows x 110 columns]

In [20]:
 final=pd.DataFrame()
 df1=df17[['FlightDate','Quarter','Year','Month','DayofMonth','DepTime','DepDel15','CRSDepTime',
        'DepDelayMinutes',
        'OriginAirportID',
        'DestAirportID',
        'ArrTime',
        'CRSArrTime',
        'ArrDel15',
        'ArrDelayMinutes',
        'Origin','Dest']]
df2=df1.loc[df1['Origin'].isin([
        'ATL',
        'CLT',
        'DEN',
        'DFW',
        'EWR',
        'IAH',
        'JFK',
        'LAS',
        'LAX',
        'MCO',
        'MIA',
        'ORD',
        'PHX',
        'SEA',
        'SFO'
        ])]
df2=df2.loc[df2['Dest'].isin(['ATL',
        'CLT',
        'DEN',
        'DFW',
        'EWR',
        'IAH',
        'JFK',
        'LAS',
        'LAX',
        'MCO',
        'MIA',
        'ORD',
        'PHX',
        'SEA',
        'SFO'])]
final=pd.concat([df2,final])
        
final

        FlightDate  Quarter  Year  Month  ...  ArrDel15  ArrDelayMinutes  Origin  Dest
26      2016-07-01        3  2016      7  ...       1.0             22.0     JFK   LAX
27      2016-07-02        3  2016      7  ...       0.0              0.0     JFK   LAX
28      2016-07-03        3  2016      7  ...       0.0              0.0     JFK   LAX
29      2016-07-04        3  2016      7  ...       0.0              0.0     JFK   LAX
30      2016-07-05        3  2016      7  ...       1.0             21.0     JFK   LAX
...            ...      ...   ...    ...  ...       ...              ...     ...   ...
450922  2016-11-05        4  2016     11  ...       0.0              1.0     EWR   ATL
450925  2016-11-05        4  2016     11  ...       0.0              0.0     ATL   PHX
450926  2016-11-05        4  2016     11  ...       0.0              0.0     ATL   SFO
450929  2016-11-05        4  2016     11  ...       0.0              0.0     ATL   CLT
450931  2016-11-05        4  2016     11  ...       0.0              0.0     MCO   JFK

[948819 rows x 17 columns]

In [0]:
final.to_csv("/content/gdrive/My Drive/Flight/finalflight2016.csv")

In [0]:
/content/finalflight2016.csv

In [23]:
df18 = pd.concat(map(pd.read_csv, glob.glob('/content/gdrive/My Drive/Flight/217/*.csv')))

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (48,77) have mixed types. Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [24]:
df18

        Year  Quarter  Month  ...  Div5WheelsOff  Div5TailNum Unnamed: 109
0       2017        4     10  ...            NaN          NaN          NaN
1       2017        4     10  ...            NaN          NaN          NaN
2       2017        4     10  ...            NaN          NaN          NaN
3       2017        4     10  ...            NaN          NaN          NaN
4       2017        4     10  ...            NaN          NaN          NaN
...      ...      ...    ...  ...            ...          ...          ...
458722  2017        3      9  ...            NaN          NaN          NaN
458723  2017        3      9  ...            NaN          NaN          NaN
458724  2017        3      9  ...            NaN          NaN          NaN
458725  2017        3      9  ...            NaN          NaN          NaN
458726  2017        3      9  ...            NaN          NaN          NaN

[5674621 rows x 110 columns]

In [25]:
 final1=pd.DataFrame()
 df1=df18[['FlightDate','Quarter','Year','Month','DayofMonth','DepTime','DepDel15','CRSDepTime',
        'DepDelayMinutes',
        'OriginAirportID',
        'DestAirportID',
        'ArrTime',
        'CRSArrTime',
        'ArrDel15',
        'ArrDelayMinutes',
        'Origin','Dest']]
df2=df1.loc[df1['Origin'].isin([
        'ATL',
        'CLT',
        'DEN',
        'DFW',
        'EWR',
        'IAH',
        'JFK',
        'LAS',
        'LAX',
        'MCO',
        'MIA',
        'ORD',
        'PHX',
        'SEA',
        'SFO'
        ])]
df2=df2.loc[df2['Dest'].isin(['ATL',
        'CLT',
        'DEN',
        'DFW',
        'EWR',
        'IAH',
        'JFK',
        'LAS',
        'LAX',
        'MCO',
        'MIA',
        'ORD',
        'PHX',
        'SEA',
        'SFO'])]
final1=pd.concat([df2,final1])
        
final1

        FlightDate  Quarter  Year  Month  ...  ArrDel15  ArrDelayMinutes  Origin  Dest
3       2017-10-06        4  2017     10  ...       0.0              0.0     EWR   ORD
11      2017-10-06        4  2017     10  ...       0.0              0.0     IAH   ORD
15      2017-10-06        4  2017     10  ...       0.0              0.0     EWR   IAH
16      2017-10-06        4  2017     10  ...       0.0              0.0     SFO   EWR
22      2017-10-06        4  2017     10  ...       1.0             50.0     ATL   ORD
...            ...      ...   ...    ...  ...       ...              ...     ...   ...
458684  2017-09-25        3  2017      9  ...       0.0              0.0     SFO   JFK
458687  2017-09-25        3  2017      9  ...       0.0              0.0     EWR   MCO
458688  2017-09-25        3  2017      9  ...       0.0              0.0     MCO   EWR
458695  2017-09-25        3  2017      9  ...       0.0              0.0     LAS   JFK
458711  2017-09-25        3  2017      9  ...       0.0              0.0     MCO   JFK

[928477 rows x 17 columns]

In [0]:
flight=pd.concat([final,final1])

In [28]:
flight

        FlightDate  Quarter  Year  Month  ...  ArrDel15  ArrDelayMinutes  Origin  Dest
26      2016-07-01        3  2016      7  ...       1.0             22.0     JFK   LAX
27      2016-07-02        3  2016      7  ...       0.0              0.0     JFK   LAX
28      2016-07-03        3  2016      7  ...       0.0              0.0     JFK   LAX
29      2016-07-04        3  2016      7  ...       0.0              0.0     JFK   LAX
30      2016-07-05        3  2016      7  ...       1.0             21.0     JFK   LAX
...            ...      ...   ...    ...  ...       ...              ...     ...   ...
458684  2017-09-25        3  2017      9  ...       0.0              0.0     SFO   JFK
458687  2017-09-25        3  2017      9  ...       0.0              0.0     EWR   MCO
458688  2017-09-25        3  2017      9  ...       0.0              0.0     MCO   EWR
458695  2017-09-25        3  2017      9  ...       0.0              0.0     LAS   JFK
458711  2017-09-25        3  2017      9  ...       0.0              0.0     MCO   JFK

[1877296 rows x 17 columns]

In [0]:
flight.to_csv("/content/gdrive/My Drive/Flight/finalflight.csv")