In [0]:
from google.colab import drive

drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive

In [0]:

import pandas as pd
import os
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as sns
%matplotlib inline
from collections import Counter 
import matplotlib.pyplot as plt

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [0]:
m = pd.read_csv("/content/gdrive/My Drive/finalmerge.csv",index_col=0)

/usr/local/lib/python3.6/dist-packages/numpy/lib/arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [0]:
X=m.drop([
               
                "ArrTime",
              
                 "Unnamed: 0_x",
                 "Unnamed: 0_y",
                 "Unnamed: 0.1",
                "Origin",
                "Dest",
                "airport_x",
                "airport_y",
                "FlightDate",
                "date_y",
                "date_x",
                "time_x",
                "time_y",
                "windspeedKmph_y",
                "winddirDegree_y",
                "weatherCode_y",
                "precipMM_y",
                "visibility_y",
                "pressure_y",
                "cloudcover_y",
                "DewPointF_y",
                "WindGustKmph_y",
                "tempF_y",
               "WindChillF_y",
               "humidity_y",],axis=1)
X

         Quarter  Year  Month  ...  tempF_x  WindChillF_x  humidity_x
0              1  2016      1  ...       41            32          74
1              1  2016      1  ...       51            47          46
2              1  2016      1  ...       51            47          46
3              1  2016      1  ...       42            33          74
4              1  2016      1  ...       53            49          42
...          ...   ...    ...  ...      ...           ...         ...
1815400        3  2017      9  ...       74            74          87
1815401        3  2017      9  ...       65            65          91
1815402        3  2017      9  ...       67            67          75
1815403        3  2017      9  ...       68            68          80
1815404        3  2017      9  ...       72            72          78

[1815405 rows x 25 columns]

In [0]:
Y=m["ArrDel15"]
from sklearn.model_selection import train_test_split  
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = None)

In [0]:
Y_train.value_counts()

0.0    1148462
1.0     303862
Name: ArrDel15, dtype: int64

In [0]:
newX_train=X_train[X_train['ArrDel15'] == 1.0]
newX_test=X_test[X_test['ArrDel15'] == 1.0]

In [0]:
newX_train=newX_train.drop(['ArrDel15'],axis=1)
newX_test=newX_test.drop(['ArrDel15'],axis=1)

In [0]:
newY_train=newX_train[newX_train['ArrDelayMinutes'] > 0.0]
newY_test=newX_test[newX_test['ArrDelayMinutes'] > 0.0]

newY_train=newY_train['ArrDelayMinutes']
                       
newY_test=newY_test['ArrDelayMinutes']

newY_test

942859      36.0
426200      82.0
94352       21.0
971883     104.0
1431659     32.0
           ...
1002171    169.0
540396      81.0
1678962     40.0
163607      26.0
30048      278.0
Name: ArrDelayMinutes, Length: 75504, dtype: float64

In [0]:
newX_train=newX_train.drop(['ArrDelayMinutes'],axis=1)
newX_test=newX_test.drop(['ArrDelayMinutes'],axis=1)

In [0]:
newX_train

         Quarter  Year  Month  ...  tempF_x  WindChillF_x  humidity_x
964836         1  2017      1  ...       12            -4          73
1805497        3  2017      9  ...       46            43          93
1203016        4  2017     12  ...       39            34          89
777498         3  2016      8  ...       67            68          83
1478307        2  2017      5  ...       81            81          69
...          ...   ...    ...  ...      ...           ...         ...
665209         2  2016      6  ...       90            91          54
1625157        3  2017      7  ...       63            63          84
1156796        4  2017     12  ...       42            42          32
1324679        1  2017      3  ...       84            82          55
1750955        3  2017      9  ...       84            84          69

[303862 rows x 23 columns]

In [0]:
Y_test

942859     1.0
426200     1.0
338049     0.0
1054280    0.0
206897     0.0
          ...
30048      1.0
439032     0.0
1171613    0.0
74243      0.0
1482649    0.0
Name: ArrDel15, Length: 363081, dtype: float64

In [0]:
#ETR
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
from sklearn.ensemble import ExtraTreesRegressor
etr=ExtraTreesRegressor(n_jobs=-1,random_state =None)

etr.fit(newX_train,newY_train)

Y_predetr= etr.predict(newX_test)

print("RMSE :" , np.sqrt(mean_squared_error(newY_test, Y_predetr)))
print("MAE : " , mean_absolute_error(newY_test, Y_predetr))
print("R2   :" , r2_score(newY_test,Y_predetr))

RMSE : 16.95303068548153
MAE :  11.872026846259802
R2   : 0.9436266198513623

In [0]:
#LINEAR R
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(newX_train,newY_train)

Y_predlinear=reg.predict(newX_test)



print("RMSE :" , np.sqrt(mean_squared_error(newY_test, Y_predlinear)))
print("MAE : " , mean_absolute_error(newY_test, Y_predlinear))
print("R2   :" , r2_score(newY_test,Y_predlinear))

RMSE : 17.688799885032186
MAE :  12.259412873547337
R2   : 0.9398757019584925

In [0]:
#XGB
import xgboost as xgb
xgbmodel = xgb.XGBRegressor()
xgbmodel.fit(newX_train,newY_train)
Y_predxgbr = xgbmodel.predict(newX_test)

print("RMSE :" , np.sqrt(mean_squared_error(newY_test, Y_predxgbr)))
print("MAE : " , mean_absolute_error(newY_test, Y_predxgbr))
print("R2   :" , r2_score(newY_test,Y_predxgbr))

[18:07:57] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
RMSE : 17.041398284675694
MAE :  11.732441591352789
R2   : 0.9441962049631047

In [0]:
#resampling

In [0]:
X_train=X_train.drop(['ArrDel15'],axis=1)
X_test=X_test.drop(['ArrDel15'],axis=1)

In [0]:
#resampling to make the 0 and 1 values equal 
X = pd.concat([X_train, Y_train], axis=1)
X=X.drop(['ArrDelayMinutes'],axis=1)
X

         Quarter  Year  Month  ...  WindChillF_x  humidity_x  ArrDel15
1512726        2  2017      6  ...            97           9       0.0
964836         1  2017      1  ...            -4          73       1.0
1175044        4  2017     12  ...            58          59       0.0
1805497        3  2017      9  ...            43          93       1.0
946990         1  2017      1  ...            55          91       0.0
...          ...   ...    ...  ...           ...         ...       ...
150958         4  2016     11  ...            61          91       0.0
1512763        2  2017      6  ...            77          69       0.0
983284         1  2017      1  ...            39          95       0.0
1620548        3  2017      7  ...            90          65       0.0
1560608        2  2017      6  ...            61          74       0.0

[1452324 rows x 24 columns]

In [0]:
not_delayed = X[X.ArrDel15==0]
delayed = X[X.ArrDel15==1]

In [0]:
from sklearn.utils import resample
delayed_upsampled = resample(delayed,replace=True, n_samples=len(not_delayed),random_state=27)

In [0]:
upsampled = pd.concat([not_delayed, delayed_upsampled])

In [0]:
upsampled.ArrDel15.value_counts()

1.0    1148462
0.0    1148462
Name: ArrDel15, dtype: int64

In [0]:
upsampled

         Quarter  Year  Month  ...  WindChillF_x  humidity_x  ArrDel15
1512726        2  2017      6  ...            97           9       0.0
1175044        4  2017     12  ...            58          59       0.0
946990         1  2017      1  ...            55          91       0.0
535300         2  2016      5  ...            61          48       0.0
20150          1  2016      1  ...            20          90       0.0
...          ...   ...    ...  ...           ...         ...       ...
289302         4  2016     12  ...            69          38       1.0
99805          4  2016     10  ...            79          21       1.0
1324263        1  2017      3  ...            56          25       1.0
168095         4  2016     11  ...            57          91       1.0
911721         3  2016      9  ...            54          84       1.0

[2296924 rows x 24 columns]

In [0]:
#values are equal now
y_train = upsampled.ArrDel15
x_train = upsampled.drop(['ArrDel15'], axis=1)

In [0]:
y_train.value_counts()

1.0    1148462
0.0    1148462
Name: ArrDel15, dtype: int64

In [0]:
#y_train.value_counts()

In [0]:

#decision tree
from sklearn.tree import DecisionTreeClassifier

clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [0]:
X_test=X_test.drop(['ArrDelayMinutes'],axis=1)

In [0]:
y_pred2 = clf.predict(X_test)

In [0]:
from sklearn.metrics import classification_report

print(classification_report(Y_test, y_pred2))

              precision    recall  f1-score   support

         0.0       0.92      0.92      0.92    287059
         1.0       0.70      0.70      0.70     76022

    accuracy                           0.87    363081
   macro avg       0.81      0.81      0.81    363081
weighted avg       0.87      0.87      0.87    363081

In [0]:
#extra tree 
from sklearn.ensemble import ExtraTreesClassifier
etc=ExtraTreesClassifier(n_jobs=-1,random_state =None)
etc.fit(x_train,y_train)

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
                     oob_score=False, random_state=None, verbose=0,
                     warm_start=False)

In [0]:
Y_predetc=etc.predict(X_test)

In [0]:
target_names=["Class 0","Class 1"]
from sklearn.metrics import classification_report

print(classification_report(Y_test,Y_predetc,target_names=target_names))

              precision    recall  f1-score   support

     Class 0       0.93      0.95      0.94    287577
     Class 1       0.81      0.73      0.77     75504

    accuracy                           0.91    363081
   macro avg       0.87      0.84      0.86    363081
weighted avg       0.91      0.91      0.91    363081

In [0]:

Y_predetc
xtdf=pd.DataFrame(Y_predetc)
xtdf[0]
X_test["ArrDelayMinutes"]=m["ArrDelayMinutes"]
X_test

         Quarter  Year  Month  ...  WindChillF_x  humidity_x  ArrDelayMinutes
942859         1  2017      1  ...            58          96             36.0
426200         1  2016      3  ...            13          84             82.0
338049         1  2016      2  ...            43          58              0.0
1054280        4  2017     10  ...            65          50              0.0
206897         4  2016     11  ...            79          42              0.0
...          ...   ...    ...  ...           ...         ...              ...
30048          1  2016      1  ...            57          88            278.0
439032         1  2016      3  ...            59          88              0.0
1171613        4  2017     12  ...            60          53              0.0
74243          4  2016     10  ...            65          83              0.0
1482649        2  2017      5  ...            68          41              4.0

[363081 rows x 24 columns]

In [0]:
X.transpose()

                 0        1        2        ...  1815402  1815403  1815404
Quarter              1.0      1.0      1.0  ...      3.0      3.0      3.0
Year              2016.0   2016.0   2016.0  ...   2017.0   2017.0   2017.0
Month                1.0      1.0      1.0  ...      9.0      9.0      9.0
DayofMonth           1.0      1.0      1.0  ...     22.0     23.0     24.0
DepTime            741.0    705.0    658.0  ...   2240.0   2146.0   2246.0
DepDel15             0.0      0.0      0.0  ...      0.0      0.0      0.0
CRSDepTime         700.0    700.0    700.0  ...   2200.0   2100.0   2200.0
DepDelayMinutes      0.0      0.0      3.0  ...      0.0      3.0      1.0
OriginAirportID  14747.0  14747.0  14747.0  ...  12478.0  12478.0  12478.0
DestAirportID    12478.0  12892.0  12892.0  ...  12892.0  12892.0  12892.0
CRSArrTime        1600.0    900.0    900.0  ...    200.0    100.0    200.0
windspeedKmph_x     22.0     12.0     12.0  ...     10.0      6.0      4.0
winddirDegree_x    255.0     31.0     31.0  ...    135.0    202.0    193.0
weatherCode_x      113.0    113.0    113.0  ...    113.0    113.0    113.0
precipMM_x           0.0      0.0      0.0  ...      0.0      0.0      0.0
visibility_x        10.0     10.0     10.0  ...     10.0     10.0     10.0
pressure_x        1015.0   1020.0   1020.0  ...   1010.0   1009.0   1011.0
cloudcover_x         0.0      2.0      2.0  ...      3.0      4.0      3.0
DewPointF_x         32.0     30.0     30.0  ...     59.0     61.0     64.0
WindGustKmph_x      26.0     15.0     15.0  ...     12.0      8.0      6.0
tempF_x             41.0     51.0     51.0  ...     67.0     68.0     72.0
WindChillF_x        32.0     47.0     47.0  ...     67.0     68.0     72.0
humidity_x          74.0     46.0     46.0  ...     75.0     80.0     78.0
Arrdel15             0.0      0.0      0.0  ...      0.0      0.0      0.0
ArrDelayMinutes      8.0      0.0      0.0  ...      0.0      0.0      0.0

[25 rows x 1815405 columns]

In [0]:
import collections

classified_df = pd.DataFrame(X_test)

classified_df['Arrdel15']=Y_predetc

In [0]:
classified_df.to_csv("finalpipeline.csv")

pipeline

In [0]:
df3 = pd.read_csv("finalpipeline.csv",index_col=0)
df3

         Quarter  Year  Month  ...  humidity_x  ArrDelayMinutes  Arrdel15
942859         1  2017      1  ...          96             36.0       1.0
426200         1  2016      3  ...          84             82.0       1.0
338049         1  2016      2  ...          58              0.0       0.0
1054280        4  2017     10  ...          50              0.0       0.0
206897         4  2016     11  ...          42              0.0       0.0
...          ...   ...    ...  ...         ...              ...       ...
30048          1  2016      1  ...          88            278.0       1.0
439032         1  2016      3  ...          88              0.0       1.0
1171613        4  2017     12  ...          53              0.0       0.0
74243          4  2016     10  ...          83              0.0       0.0
1482649        2  2017      5  ...          41              4.0       0.0

[363081 rows x 25 columns]

In [0]:
X3=df3.loc[df3['Arrdel15'] == 1.0]      #selecting only delayed flights 
X3.shape

(68838, 25)

In [0]:
Y3 = X3['ArrDelayMinutes']
Y3

942859      36.0
426200      82.0
94352       21.0
971883     104.0
1431659     32.0
           ...
540396      81.0
1678962     40.0
1035883      9.0
30048      278.0
439032       0.0
Name: ArrDelayMinutes, Length: 68838, dtype: float64

In [0]:
X3=X3.drop(['ArrDelayMinutes','Arrdel15'],axis = 1)

In [0]:
#linear
Y_predlinear=reg.predict(X3)



print("RMSE :" , np.sqrt(mean_squared_error(Y3, Y_predlinear)))
print("MAE : " , mean_absolute_error(Y3, Y_predlinear))
print("R2   :" , r2_score(Y3,Y_predlinear))

RMSE : 18.85196646333084
MAE :  14.036548405228274
R2   : 0.9397474260950494

In [0]:
preddfe = pd.DataFrame({'Actual': Y3, 'Predicted': Y_predlinear})
preddfe

         Actual   Predicted
335869     64.0   90.985663
1544872    72.0   94.042052
1570502   119.0   48.531276
6398       65.0  100.907765
1136778   113.0   88.359604
...         ...         ...
722677     56.0   24.925437
1480869    84.0   75.395486
100520    188.0  185.573106
579439     62.0   68.065194
1097647    61.0   66.441583

[69506 rows x 2 columns]

In [0]:
#xgb
Y_predxgbr = xgbmodel.predict(X3)

print("RMSE :" , np.sqrt(mean_squared_error(Y3, Y_predxgbr)))
print("MAE : " , mean_absolute_error(Y3, Y_predxgbr))
print("R2   :" , r2_score(Y3,Y_predxgbr))

RMSE : 19.229057228653627
MAE :  14.481891775571661
R2   : 0.9373128867445829

In [0]:
preddfe1 = pd.DataFrame({'Actual': Y3, 'Predicted': Y_predxgbr})
preddfe1

         Actual   Predicted
335869     64.0   92.109673
1544872    72.0   92.768623
1570502   119.0   47.851517
6398       65.0   99.513794
1136778   113.0   88.292862
...         ...         ...
722677     56.0   34.449196
1480869    84.0   71.192215
100520    188.0  188.403183
579439     62.0   64.034058
1097647    61.0   62.633236

[69506 rows x 2 columns]

In [0]:
X_test

         Quarter  Year  Month  ...  humidity_x  ArrDelayMinutes  Arrdel15
1569300        2  2017      6  ...          49              0.0       0.0
350257         1  2016      2  ...          95              0.0       0.0
1811198        3  2017      9  ...          90             15.0       0.0
1055669        4  2017     10  ...          92              0.0       0.0
1318502        1  2017      3  ...          52              0.0       0.0
...          ...   ...    ...  ...         ...              ...       ...
1154841        4  2017     12  ...          52              0.0       0.0
1194583        4  2017     12  ...          75              0.0       0.0
306655         1  2016      2  ...          78              0.0       0.0
939820         1  2017      1  ...          67              6.0       0.0
1001157        4  2017     10  ...          59              0.0       0.0

[363081 rows x 25 columns]

In [0]:
#etr


Y_predetr= etr.predict(X3)

print("RMSE :" , np.sqrt(mean_squared_error(Y3, Y_predetr)))
print("MAE : " , mean_absolute_error(Y3, Y_predetr))
print("R2   :" , r2_score(Y3,Y_predetr))

RMSE : 19.39842174928299
MAE :  14.616127720154566
R2   : 0.9350477973154084

In [0]:
preddfe2 = pd.DataFrame({'Actual': Y3, 'Predicted': Y_predetr})
preddfe2

         Actual  Predicted
942859     36.0      40.92
426200     82.0      72.11
94352      21.0      34.82
971883    104.0     103.37
1431659    32.0      34.96
...         ...        ...
540396     81.0      89.88
1678962    40.0      43.94
1035883     9.0      48.64
30048     278.0     316.06
439032      0.0      27.57

[68838 rows x 2 columns]